FROM centos:7
MAINTAINER misho-kr@github.com

RUN rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm

RUN \
    yum install -y zabbix-web-mysql && \
    systemctl enable httpd

RUN \
    sed -e 's/.*php_value date\.timezone.*$/    php_value date\.timezone America\/Los_Angeles/' \
        -i /etc/httpd/conf.d/zabbix.conf

ENTRYPOINT ["/usr/sbin/init"]
