FROM centos:7
MAINTAINER misho-kr@github.com

RUN rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm

RUN \
    yum install -y zabbix-server zabbix-server-mysql && \
    systemctl enable zabbix-server

RUN \
    sed -e 's/.*DBHost=.*$/DBHost=db/'                         \
        -e 's/.*DBPassword=.*$/DBPassword=zabbix-password/'    \
        -i /etc/zabbix/zabbix_server.conf

ENTRYPOINT ["/usr/sbin/init"]
